sampler:
  target: sampler.QDMSampler

model:
  target: models.dit.QDM
  ckpt_path: ~
  params:
    input_size: 128
    up_patch_size: 8
    down_patch_size: 2
    down_large_patch_size: 8
    in_channels: 3
    hidden_size: 768
    depth: 6
    num_heads: 12
    mlp_ratio: 4.0
    learn_sigma: False
    cond_lq: True
    lq_channels: 3

data:
  chn: rgb
  im_exts: ["png", "jpeg", "jpg"]

diffusion:
  target: models.script_util.create_masked_gaussian_diffusion
  params:
    sf: 8
    schedule_name: exponential
    schedule_kwargs:
      power: 0.3
    etas_end: 0.99
    steps: 15
    min_noise_level: 0.04
    kappa: 2.0
    weighted_mse: False
    predict_type: xstart
    timestep_respacing: ~
    scale_factor: 0.1
    normalize_input: True
    latent_flag: True

autoencoder:
  target: ldm.models.autoencoder.AutoencoderKLTorch
  ckpt_path: weights/medical_autoencoder.ckpt
  use_fp16: True
  params:
    embed_dim: 3    
    ddconfig:
      double_z: True
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

inference:
  sf: 8
  threshold: 0.15
  mask_forward: True
  chunk_size: 64
  noise_repeat: False

